name: Electron Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      version_name:
        type: string
        description: "Desktop Version name eg: 5.6"
        required: true
      platform:
        type: choice
        description: "Choose platform to run tests"
        required: true
        default: "all"
        options: [linux, macos, windows, all]

jobs:
  determine-platforms:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.set-matrix.outputs.platforms }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ inputs.platform }}" == "all" ]]; then
              echo "platforms=['ubuntu-22.04', 'macos-13', 'windows-2022']" >> $GITHUB_OUTPUT
            else
              case "${{ inputs.platform }}" in
                linux)  echo "platforms=['ubuntu-22.04']" ;;
                macos)  echo "platforms=['macos-13']" ;;
                windows) echo "platforms=['windows-2022']" ;;
              esac >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.event_name }}" == "push" ]] || [[ "${{ contains(github.event.pull_request.labels.*.name, 'Run Desktop E2E Tests') }}" == "true" ]]; then
            echo "platforms=['ubuntu-22.04', 'macos-13', 'windows-2022']" >> $GITHUB_OUTPUT
          else
            echo "platforms=[]" >> $GITHUB_OUTPUT
          fi

  e2e-tests:
    needs: determine-platforms
    strategy:
      matrix:
        os: ${{ fromJson(needs.determine-platforms.outputs.platforms) }}
      fail-fast: false
    uses: ./.github/workflows/e2e-functional-template.yml
    secrets: inherit
    with:
      runs-on: ${{ matrix.os }}
      DESKTOP_VERSION: ${{ inputs.version_name || github.head_ref || github.ref }}

  e2e-remove-label:
    if: ${{ always() && contains(github.event.pull_request.labels.*.name, 'Run Desktop E2E Tests') }}
    needs: e2e-tests
    runs-on: ubuntu-22.04
    env:
      COMMENT_BODY_LINUX: "${{ needs.e2e-linux.outputs.COMMENT_BODY_LINUX }}"
      COMMENT_BODY_MACOS: "${{ needs.e2e-macos.outputs.COMMENT_BODY_MACOS }}"
      COMMENT_BODY_WINDOWS: "${{ needs.e2e-windows.outputs.COMMENT_BODY_WINDOWS }}"
    steps:
      - name: e2e/unify-comments-in-single-comment
        run: |
          echo "PR_COMMENT<<EOF" >> "${GITHUB_ENV}"
          echo "Here are the test results below:" >> "${GITHUB_ENV}"
          echo "$COMMENT_BODY_LINUX" >> "${GITHUB_ENV}"
          echo "$COMMENT_BODY_MACOS" >> "${GITHUB_ENV}"
          echo "$COMMENT_BODY_WINDOWS" >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"

      - name: e2e/send-comment-results-in-pr
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.PR_COMMENT,
            });

      - name: Remove E2E test label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        continue-on-error: true # Label might have been removed manually
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Run Desktop E2E Tests',
            });